---
title: "La importancia del respeto a los contratos"
author: "Raul Eyzaguirre"
output: html_document
---

En pocos días se leerá el fallo de La Haya sobre el diferendo marítimo entre Perú y Chile. Soy de la idea de que el asunto territorial es el menos importante en toda esta historia, ya que dudo mucho que un poco más o un poco menos de mar vaya a tener algún efecto en el desarrollo futuro del Perú o Chile. Soy de los que cree que la verdadera riqueza de los países está en su gente, y que ser reconocida como una nación respetuosa de las leyes y los contratos tiene más valor que cualquier posesión territorial.

Al respecto se me viene a la mente el Mercader de Venecia de William Shakespeare. En los tiempos de Shakespeare Venecia era  un importante puerto comercial. Como todos sabemos, para que los negocios funcionen se requiere dinero en movimiento, por lo que los prestamistas, tan viejos seguramente como el dinero, eran esenciales.

La necesidad de contar con prestamistas trajo un problema moral en la época ya que para el cristianismo, religión al parecer predominante en Venecia, la usura era pecado (supongo que lo seguirá siendo, ¿algún cristiano por ahí que me quiera prestar plata?), y vamos, considerando los riesgos que uno afronta en cualquier negocio, nadie en su sano juicio va a estar prestando plata sin interés. El interés no es más que el pago que uno hace para poder disponer de dinero por adelantado, y cubre entre otras cosas, el riesgo asumido por el prestamista por la eventualidad del no pago. Felizmente la moral siempre va de la mano con la hipocresía, y cuando hay dinero de por medio, la hipocresía por supuesto es la que marca el paso. Para los judíos la usura también era pecado, pero con una excepción. Su religión les prohibía prestar con interés a sus hermanos, esto es, a otros judíos, pero no decía nada sobre prestarle con interés a los cristianos o a cualquiera que no fuese judío. De esta manera se instalan en la ciudad los judíos prestamistas, que eran por cierto muy mal vistos por la mayoría cristiana, pero como en toda sociedad próspera y moderna, lo de la hipocresía creo que ya lo mencioné, tolerados como un mal necesario.

En el Mercader de Venecia, Shylock, el judío prestamista, le presta un dinerito a Bassanio, amigo de Antonio, para que pueda atender algunos asuntos personales. Antonio, habría que decirlo, es el Mercader de Venecia, hombre rico que sirve de garante a Bassanio ante Shylock. La nota curiosa en la historia la pone Shylock con la condición que impone a Antonio como garante del préstamo en el contrato, firmado ante notario público que por supuesto en la época ya los había. Por artilugios de la trama, lea el libro si le interesa conocer los detalles, Shylock decide no cobrar interés en esta ocasión, y pone como única condición cobrarse con una libra de carne del propio Antonio en caso este no pueda devolver el dinero prestado en la fecha indicada.

Llegada la fecha del pago, por problemas con el clima principalmente, Antonio no tiene el dinero para cancelar el préstamo, por lo que Shylock decide exigir su libra de carne. A cualquiera de nosotros esta condición nos parecerá atroz. Ciertamente también lo debió parecer en la época que, en contra de lo que seguramente la mayoría cree, la condición humana con sus tiernos sentimientos aparentemente poco ha cambiado desde los tiempos de Shakespeare. El asunto es que el pago en carne viva pareció brutal y despiadado a todos, salvo a Shilock por supuesto, muy influenciado por el también muy humano sentimiento de la venganza.

Es así que Shilock decide llevar el pleito ante el dux de Venecia, máxima autoridad de la ciudad. Lo curioso es que, contra lo que cualquiera esperaría, el dux se siente obligado a respetar el contrato y satisfacer a Shilock. ¿Por qué? Pues por el valor del respeto a los contratos. Venecia era un puerto próspero y parte de su prosperidad, al menos así lo deja entrever Shakespeare, se debía a su tradición de respeto a las leyes y los contratos. Es muy interesante lo claro que tenía Shakespeare y el pueblo veneciano, hace más de 400 años, la importancia y el valor del respeto a los contratos, no solo como algo etéreo relacionado con altos ideales o nobles principios, sino también, y quizá principalmente, por su valor comercial, monetario, tan asociado a la prosperidad de un pueblo. Es interesante también como hoy en día hay tantas personas y tantos gobiernos, no cito ejemplos que todos sabemos que abundan, que no terminan de entender esto.

¿Se llevó al final Shilock su libra de carne? No. Si quiere conocer los detalles, lea le libro, le va a gustar.