
## ----echo=F, fig.width=10, fig.height=3.5--------------------------------
par(mfrow=c(1,3))
muestras <- array(rnorm(5000,0,1),c(1000,5))
medias <- apply(muestras,1,mean)
desves <- apply(muestras,1,sd)
plot(medias, desves, xlab=expression(bar(x)), ylab="s", main="N(0,1)")
muestras <- array(rt(5000,3),c(1000,5))
medias <- apply(muestras,1,mean)
desves <- apply(muestras,1,sd)
plot(medias, desves, xlab=expression(bar(x)), ylab="s", main=expression(t[3]))
muestras <- array(rbeta(5000,2,10),c(1000,5))
medias <- apply(muestras,1,mean)
desves <- apply(muestras,1,sd)
plot(medias, desves, xlab=expression(bar(x)), ylab="s", main="Beta(2,10)")
