---
title: "Visualización de encuestas presidenciales"
author: "Raul Eyzaguirre"
date: "20 de diciembre del 2015"
output: html_document
---

Salieron los resultados de la [última encuesta nacional urbano rural de GFK](http://larepublica.pe/politica/727453-elecciones-2016-keiko-fujimori-y-alan-garcia-bajan-puntos-en-intencion-de-voto) sobre la intención de voto para las elecciones del 2016 y los resultados son:

* Keiko Fujimori: 30%
* Pedro Pablo Kuczynski: 11%
* César Acuña: 8%
* Alan García: 5%
* Alejandro Toledo: 3%
* Julio Guzmán: 2%
* Daniel Urresti: 2%
* Verónika Mendoza: 2%
* Renzo Reggiardo: 1% 

¿Cómo se interpretan estos resultados? No hay que olvidar que aquí hay un margen de error. Eventualmente los medios de comunicación indican el margen de error y mencionan algo sobre cierto nivel de confianza, pero estos datos suelen ser incomprendidos por la mayoría. ¿Por qué hay un margen de error? Pues porque los números que se muestran son el resultado de una encuesta en la que solo se ha consultado a una pequeña parte de la población. Suponga por ejemplo que usted toma una muestra al azar de 100 personas y que en esa muestra encuentra que 30 tienen intención de votar por el candidato A. Entonces puede decir que el 30% de su muestra piensa votar por A, pero eso no quiere decir que el 30% de la población vaya a votar por A, y tampoco quiere decir que en otra muestra de 100 nuevamente 30 vayan a indicar que piensan votar por A. Si se sacaran muchas muestras de tamaño 100, en cada muestra se podrían obtener resultados distintos a favor de A; quizá 30 en algunas, 28 en otras, o 29, 33, 32, o 25, en fin, números distintos pero que si se hicieron bien las cosas en el muestreo, debieran estar todos ellos alrededor de la intención de voto poblacional, desconocida, a favor de dicho candidato. Esta variabilidad de muestra a muestra es la que tiene que ver con el margen de error.

¿Cómo visualizar entonces el resultado de una encuesta junto con su correspondiente margen de error? Una forma es calcular un intervalo de confianza. Otra forma, y la que me permito mostrar aquí, podría ser mostrando una posible distribución de los resultados que podrían obtenerse si se repitiera la encuesta muchas veces, en el supuesto, claro está, de que la única encuesta que sí se hizo, se hizo bien. La idea es, a partir de los resultados de la encuesta que sí se hizo, simular resultados de otras posibles encuestas para poder visualizar el famoso margen de error. Los resultados de estas simulaciones se pueden graficar de varias maneras: en este caso he escogido un gráfico de puntos. Abajo puede ver el resultado obtenido con la simulación de 1000 encuestas.

```{r fig.height=6, fig.width=10}
library(ggplot2)

p <- c(0.3, 0.11, 0.08, 0.05, 0.03, 0.02, 0.02, 0.02, 0.01)
n <- 1267
e <- (p * (1 - p) / n)^0.5

set.seed(1)
psim <- rnorm(9000, p, e)
candidato <- rep(c("KF", "PPK", "CA", "AG", "AT", "JG", "DU", "VM", "RR"), 1000)
candidato <- factor(candidato, levels = c("KF", "PPK", "CA", "AG", "AT", "JG", "DU", "VM", "RR"))

datos <- data.frame(p = psim, candidato = candidato)

qp <- qplot(candidato, p, data = datos, position = position_jitter(w = 0.05), alpha = I(1/8),
            color = candidato, xlab = "Candidato", ylab = "Intención de voto")
qp + theme(legend.position = "none")
```
