---
title: "La prensa y los riesgos relativos"
author: "Raul Eyzaguirre"
output: html_document
---

El día de ayer me topé con esta noticia en un conocido medio local: [Consumo frecuente de pastillas anticonceptivas duplica riesgo de padecer glaucoma. Investigadores detallan que las mujeres que han tomado anticonceptivos orales por más de tres años tienen 2.05 veces más riesgo de ser diagnosticadas con este mal](http://larepublica.pe/24-11-2013/consumo-frecuente-de-pastillas-anticonceptivas-duplica-riesgo-de-padecer-glaucoma).

En una [entrada anterior](https://reyzaguirre.wordpress.com/2013/10/09/antenas-celulares-cancer-y-mas/) ya les he comentado sobre el riesgo relativo (RR), una medida muy usada en estudios epidemiológicos y que indica cuánto más o menos probable es sufrir cierta enfermedad cuando uno se expone a determinada condición (llamado factor de exposición). Lo que dice la nota de prensa anterior es que, según cierto estudio, tomar anticonceptivos orales por más de tres años tiene un RR de 2.05 para glaucoma. La literatura científica está plagada de este tipo de estudios en donde uno puede encontrar que [casi cualquier cosa es un factor de riesgo para ciertas enfermedades (RR mayor a 1)](https://reyzaguirre.wordpress.com/2013/10/11/el-agua-bendita-causa-cancer/) y un factor de protección para ciertas otras (RR menor a 1). Por ejemplo, buscando en el mismo medio encontré [esta otra nota](http://larepublica.pe/09-08-2012/pildoras-anticonceptivas-protegerian-contra-el-cancer-de-ovario) en donde se dice que las píldoras anticonceptivas son un factor de protección para el cáncer de ovario.

Hay que tener mucho cuidado con la interpretación del RR. Lamentablemente, este tipo de estudios, algunos serios y otros no tanto, tienen mucho eco en los medios de prensa, los cuales suelen mencionarlos, que informar o comentar creo que les queda grande, con, a mi juicio, bastante irresponsabilidad.  En esta ocasión quiero solamente hacer hincapié en un detalle a tener en cuenta sobre la interpretación del RR. Decir que se tiene un RR de 2 sin más detalles es irresponsable e incompleto, ya que ese solo dato no dice mucho. Un RR de 2 puede ser un dato a considerar en ciertos casos y una medida casi irrelevante en otros. Si la enfermedad en cuestión es bastante frecuente, afectando por ejemplo a uno de cada 20 entre las personas no expuestas a cierto factor, un RR de 2 para el factor en estudio es de absoluta relevancia, pues indicaría que el factor de exposición duplica la probabilidad de desarrollar la enfermedad llevándola de 5% a 10%. Personalmente no quisiera correr ese riesgo. Sin embargo si la enfermedad en cuestión es muy poco frecuente, con por ejemplo una prevalencia de 1 por millón, entonces un RR de 2 podría considerarse como un dato intrascendente, ya que si bien duplica la probabilidad de desarrollar la enfermedad, pasar de 0.0001% a 0.0002% no implica, al menos para mí, mayor preocupación.