---
title: "Tenga su pastilla"
author: "Raúl Eyzaguirre"
output: html_document
---

Mucho se habla de la libertad como un derecho inalienable pero, ¿qué es ser libre? En primera instancia diré que para ser libre hay que estar educado en todas las materias, tanto en historia como en matemática, biología o economía, con todo el rigor que se pueda dar en una educación escolar de calidad. De ahí que me fastidien tanto todos estos políticos de pacotilla que tenemos, que se llenan la boca hablando de justicia social sin mencionar a la educación; justicia social sin educación es simplemente imposible. Pero ahora me quiero ocupar de un campo un poco más restringido, el de la estadística. ¿Puede un ciudadano común ser libre en la era de la información cuando no tiene acceso a los datos y, cuando aun teniéndolos, no tiene las herramientas para juzgar lo que dicen los datos? Supongamos que me enfermo y que el médico me receta una medicina. Yo quisiera poder ir a la web y tener libre acceso a todos los ensayos clínicos sobre esa medicina, y no solo a los ensayos clínicos sino a los datos, y por supuesto tener los conocimientos estadísticos para poder analizar e interpretar esos datos (y también los conocimientos de fisiología, farmacocinética, bioquímica, etc). Ciertamente pretender que todo el mundo esté en condiciones de hacer una evaluación acertada de los datos es una fantasía. Por eso la era de la información es también la era de la confianza, pero sin duda alguna el binomio información-confianza funcionaría mejor si todo el mundo tuviera al menos los conceptos estadísticos básicos para orientarse medianamente, si no en el terreno del análisis de la información, sí en el terreno de la confianza, esto es, poder al menos juzgar con cierto espíritu crítico no los datos pero sí al que analiza los datos. El asunto es de hecho complicado, pero empiezo a convencerme de que la estadística que se enseña en las universidades en casi todas las carreras está mal enfocada. Se enseña estadística para que el profesional pueda manejar datos en su trabajo pero no en su vida. Y entonces cuando el médico nos receta A, tomamos A sin chistar, y peor aun cuando algún charlatán nos dice que tomando un licuado con pepitas de B nos vamos a curar, muchos toman el licuado sin chistar. Y digo peor aún porque la medicina A al menos tiene, supuestamente, una pila de evidencia a su favor, y es que estaremos de acuerdo en que "tener supuestamente" es más que "no tener" (y cuando hablo de charlatanes no me estoy refiriendo a la medicina tradicional, que ésta también suele tener una ruma de evidencia a sus espaldas, acumulada durante siglos o incluso milenios). Bueno, he tomado el asunto de la medicina por ser un tema de suma importancia, pero lo expuesto aplica a cualquier tema de interés en nuestras vidas. Les comparto algunos enlaces con ejemplos ilustrativos al respecto.

[http://www.nytimes.com/2013/07/14/opinion/sunday/do-clinical-trials-work.html?pagewanted=all&_r=1](http://www.nytimes.com/2013/07/14/opinion/sunday/do-clinical-trials-work.html?pagewanted=all&_r=1)

[http://prescriptions.blogs.nytimes.com/2012/01/17/new-questions-raised-about-tamiflus-effectiveness/](http://prescriptions.blogs.nytimes.com/2012/01/17/new-questions-raised-about-tamiflus-effectiveness/)

[http://pipeline.corante.com/archives/2012/03/29/sloppy_science.php](http://pipeline.corante.com/archives/2012/03/29/sloppy_science.php)

El problema ciertamente no es la medicina, el problema es que el conocimiento científico, en cualquier área, avanza en base a datos y al análisis de los datos, y con millones de investigadores en todo el mundo, miles de revistas científicas para publicar resultados, cientos de métodos estadísticos de análisis y decenas de programas estadísticos, cada vez se hace más difícil evaluar la calidad de una publicación y la veracidad de sus resultados. Hay una cita atribuida a John Nesbit en la web: "We are drowning in information but starving for knowledge" que bien resume la situación. Vivimos en la era de la información y paradójicamente, al menos en lo que ha investigación científica se refiere, no hay nada más oscuro y guardado bajo siete llaves que los datos experimentales sobre los que descansan las conclusiones de una investigación. Soy de la idea de que las cosas mejorarán cuando se empiece a exigir a los investigadores la publicación de sus datos y protocolos de investigación en lugar de sus análisis y conclusiones. Creo que ese tiempo está cerca y por lo tanto hay que estar preparados.