---
title: "El agua bendita causa cáncer"
author: "Raul Eyzaguirre"
output: html_document
---

Desde hace algunos años estamos viviendo una epidemia de reportes sobre distintos factores de exposición que causan cáncer, y en general, cualquier tipo de enfermedad. Así tenemos que el pollo a la brasa causa cáncer, los teléfonos celulares causan cáncer, los transgénicos por supuesto causan cáncer, y me atrevería a apostar que debe haber por ahí algún estudio que diga que hasta el agua bendita causa cáncer. No soy médico y por lo tanto no voy a poner en tela de juicio a ninguno de estos reportes en particular, que seguro algunos o muchos son ciertos, pero como estadístico me quiero ocupar de todos ellos en general.

En una [entrada anterior](https://reyzaguirre.wordpress.com/2013/10/09/antenas-celulares-cancer-y-mas/) les comenté sobre la preocupación de los vecinos de San Isidro por las antenas de telefonía celular que hay en su distrito, las cuales son consideradas como causantes de cierto tipo de cáncer, y aproveché esa entrada para definir lo que en epidemiología se conoce como un factor de riesgo y un factor de protección. Al parecer lo que tenemos hoy en día es una especie de epidemia de estudios epidemiológicos reportando a casi todo como factor de riesgo para ciertas enfermedades y, hay que decirlo también, a ese mismo casi todo como factor de protección para otras tantas. Con el desarrollo actual de las comunicaciones y el sensacionalismo propio de los medios de prensa (de acuerdo, reconozco que mi titular también es algo sensacionalista), las buenas y malas noticias corren como la pólvora, y así hoy en día estamos inundados de informes sobre alimentos y hábitos de vida que son perjudiciales para nuestra salud, y por otro lado también de curas milagrosas para casi todo.

Parte del problema es esta aparente epidemia de estudios epidemiológicos. Al parecer hay mucha gente trabajando en epidemiología jugando de alguna manera a la lotería, esto es, realizando tantos estudios como les sea posible a la búsqueda de encontrar algún resultado significativo (el resultado de una investigación es significativo si aporta suficiente evidencia, medida probabilísticamente, sobre la validez de la hipótesis del investigador. ¿Qué es suficiente evidencia? El tema es algo complicado, incluso para los mismos investigadores, pero les prometo hablar de esto en el futuro). Al respecto me topé con [esta presentación](http://www.niss.org/sites/default/files/Young_Safety_June_2008.pdf) que arroja un dato elocuente: "Empirical evidence is that 80-90% of the claims made by epidemiologists are false; these claims do not replicate when retested under rigorous conditions". En castellano lo que dice es que se calcula que entre el 80 y 90% de los resultados de los estudios epidemiológicos son falsos, ya que estos resultados no se pueden replicar cuando las hipótesis de investigación son evaluadas nuevamente bajo condiciones rigurosas. ¿Qué les parece?