---
title: "Entropía e información"
author: "Raul Eyzaguirre"
date: "November 11, 2015"
output: html_document
---

Más de uno debe haberse preguntado en algún momento para qué sirven los logaritmos. El cálculo no es complicado, para eso están las computadoras, y en cualquier caso lo que uno tiene que hacer es sencillamente evaluar alguna fórmula, pero, volviendo al punto de partida, ¿para qué sirven los logaritmos? ¿Qué hay más allá de las fórmulas y el mero cálculo? Obviamente sirven, y mucho, ejemplos hay para escoger, y aquí quiero ponerles uno pensando en mis amigos ecólogos, y en particular en el famoso índice de Shannon, utilizado para evaluar la diversidad de un ecosistema.

Empecemos con una idea sencilla. Imagine dos cajas, una de ellas con un premio. ¿Cuántas preguntas con respuesta del tipo sí/no se necesitan para tener la seguridad de descubrir en qué caja está el premio? En este caso una pregunta será suficiente, bastará con preguntar por ejemplo si el premio está en la caja uno, si la respuesta es sí pues el premio está en esa caja y si la respuesta es no pues estará en la otra, pero, ¿y los logaritmos? Espere un poco que ya vamos. Dos cajas y una pregunta, y note que log~2~2 = 1. ¿Se capta la idea? Bueno, talvez todavía no, así que sigamos. Imagine ahora 4 cajas, de nuevo una de ellas con un premio. ¿Cuántas preguntas necesitamos para encontrarlo? Ahora necesitaremos 2; la primera pregunta podría ser si el premio está en una caja par, y si la respuesta es no, la segunda podría ser si el premio está en la caja uno; si la respuesta a esta segunda pregunta es sí pues el premio estará en la caja uno y si es no pues estará en la caja tres. En este caso tenemos 4 cajas y 2 preguntas, y noten que log~2~4 = 2. Con 8 cajas necesitaríamos 3 preguntas y log~2~8 = 3, con 16 cajas necesitaríamos 4 preguntas y log~2~16 = 4. ¿Quedó la idea? Desde luego que sí. En general, si tuviéramos *n*=2*q* cajas necesitaríamos q preguntas para encontrar el premio, y claro, log~2~*n* = *q*.

Lo que nos ilustra el ejemplo anterior es que log~2~*n* resulta ser una medida de información, pues nos dice cuántas preguntas necesitamos para encontrar el premio. Si necesitamos más preguntas es porque necesitamos más información, lo que también podría verse como que el problema que queremos resolver entraña más incertidumbre, caos o entropía. ¿Y el índice de Shannon? Aquí vamos, simplemente fíjense que log~2~*n* = -log~2~*n*^-1^ = -$\sum$ *n*^-1^log~2~*n*^-1^, donde la suma se toma sobre las *n* cajas, y voilà, ahí está el índice de Shannon, o bueno, casi casi. Noten que en esta última expresión, *n*^-1^ representa la probabilidad de que el premio esté en una caja cualquiera escogida al azar.

La idea con el índice de Shannon en ecología es evaluar la diversidad de un ecosistema. Supongamos que estamos en eso y que hemos tomado datos de frecuencias para *K* especies en dicho ecosistema. Sea *p~i~* la proporción de individuos pertenecientes a la especie *i*. Entonces, si escogemos una caja al azar, perdón, un individuo al azar, la probabilidad de que pertenezca a la especie *i* es *p~i~*. Bueno, reemplacemos *n*-1 por *p~i~* , cambiemos el logaritmo base 2 por el natural y, ¿qué tenemos?, ¡ta tan!, -$\sum$*p~i~*ln*p~i~* , el índice de Shannon, donde la suma se efectúa sobre las *K* especies.

El índice de Shannon mide diversidad, o caos, o entropía, y si lo vemos desde el otro lado, porque para hacer una montaña también hay que hacer un hueco, mide información, la información que necesitaríamos para explicar el sistema. Si solo hubiera una especie, entonces *p* = 1 y -1ln1 = 0, esto es, no se necesita información para describir el ecosistema, y si escogieramos un individuo al azar pues la probabilidad de que pertenezca a la única especie presente sería 1, con lo que tenemos certidumbre total. Con *K* especies el índice y por lo tanto la incertidumbre en el sistema son máximos cuando todas las especies tienen la misma frecuencia, de modo que si se selecciona un individuo al azar, la probabilidad de que sea de una especie en particular es 1/*K*. Obviamente el índice tiende a subir conforme *K* aumenta.

Bueno eso es todo por hoy, espero que el ejemplo les haya gustado. Ya habrá seguro oportunidad para ver otros ejemplos con esto de los logaritmos.