---
title: "La estadística y la intuición"
author: "Raul Eyzaguirre"
date: "November 11, 2015"
output: html_document
---

En una [entrada anterior](https://reyzaguirre.wordpress.com/2013/08/22/haga-negocio-con-cuco/) les comenté que la intuición y las probabilidades no se llevan muy bien. Creo que lo que complica realmente nuestra intuición son las probabilidades condicionales. En esta ocasión quiero mencionar otro ejemplo basado en la conocida distribución *t*.

Empecemos con una definición que debe ser reconocida por quienes llevaron un curso de estadística en el pregrado. Sea $Z$ una variable aleatoria con distribución normal estándar y sea $U$ una variable aleatoria con distribución ji-cuadrado con $k$ grados de libertad. Si $Z$ y $U$ son independientes entonces la variable

$$
T=\frac{Z}{\sqrt{\frac{U}{k}}}
$$

tiene una distribución *t* de Student con $k$ grados de libertad. Leamos nuevamente la definición anterior y pongamos principal atención en la parte que dice que "$Z$ y $U$ son independientes".

Veamos ahora el siguiente conocido y muy utilizado resultado muestral: Sea $X_1, \ldots, X_n$ una muestra aleatoria extraída desde una población normal. Entonces se tiene que

$$
Z=\frac{\bar X-\mu}{\sigma/\sqrt{n}}
$$

tiene una distribución normal estándar y

$$
U=\frac{(n-1)S^2}{\sigma^2}
$$

tiene una distribución ji-cuadrado con $n-1$ grados de libertad. Luego, considerando que $Z$ y $U$ son independientes se tiene que

$$
T=\frac{Z}{\sqrt{\frac{U}{n-1}}}=\frac{\bar X-\mu}{S/\sqrt{n}}
$$

tiene una distribución *t* con $n-1$ grados de libertad. Pero, ¿son realmente $Z$ y $U$ independientes? Noten que la única variable de la que depende $Z$ es la media muestral $\bar X$ y que la única variable de la que depende $U$ es la varianza muestral $S^2$, por lo que podríamos reformular la pregunta anterior de la siguiente manera: ¿son $\bar X$ y $S^2$ independientes? Dado que $\bar X$ y $S^2$ son calculadas a partir de la misma muestra nuestra intuición salta como un resorte para decirnos que no, cuando en realidad la respuesta correcta es que sí. En efecto, dada una muestra aleatoria $X_1,\ldots,X_n$ extraída desde una población normal, se puede demostrar que $\bar X$ y $S^2$ son variables aleatorias independientes (vea por ejemplo el teorema de Cochran).

Finalmente notemos que lo anterior es cierto siempre y cuando los datos provengan de una distribución normal (no me he dado el trabajo de averiguar si existen otras distribuciones bajo las cuales esto sea cierto pero la intuición me dice que.). Si los datos tuvieran otra distribución, entonces la media y la varianza muestral no serían independientes. Abajo les muestro unos gráficos de dispersión para datos simulados desde una distribución normal estándar, una distribución *t* con 3 grados de libertad y una distribución beta(2,10).

```{r fig.height=3, fig.width=9}
par(mfrow = c(1, 3))
muestras <- array(rnorm(5000, 0, 1), c(1000, 5))
medias <- apply(muestras, 1, mean)
desves <- apply(muestras, 1, sd)
plot(medias, desves, xlab = expression(bar(x)), ylab = "s", main = "N(0, 1)")
muestras <- array(rt(5000, 3), c(1000, 5))
medias <- apply(muestras, 1, mean)
desves <- apply(muestras, 1, sd)
plot(medias, desves, xlab = expression(bar(x)), ylab = "s", main = expression(t[3]))
muestras <- array(rbeta(5000, 2, 10), c(1000, 5))
medias <- apply(muestras, 1, mean)
desves <- apply(muestras, 1, sd)
plot(medias, desves, xlab = expression(bar(x)), ylab = "s", main = "Beta(2, 10)")
```
